# Trends

This notebook looks at rates and trends in post-fire harvests between years, ecoregions, 
ownerships, and severity levels.

In [6]:
import pandas as pd
import plotly.express as px
from pfh.scripts.config import OWNER_GROUPS

## Data Prep

Load the stratified harvest area results exported from Earth Engine and process into annual trends and summaries.

In [3]:
df = pd.read_csv("../data/results/stratified_results.csv").drop(
    columns=["system:index", ".geo"]
)

# Remove unmanaged lands from analysis
df = df[~df["owner"].isin(["wilderness", "nps"])]

# Assign owner groups
df["owner_group"] = df["owner"].map(OWNER_GROUPS)

# Assign severity categories
df["severity"] = pd.Categorical(
    df["severity"], categories=["Very low", "Low", "Moderate", "High"], ordered=True
)
# Check for incorrect severity category names which will produce NAs
assert not df.isna().any().any(), "Check severity category names!"

# Collapse all timings to simplify future processing where having multiple timings
# could lead to multi-counting areas.
df_all_timings = (
    df.groupby(["event_id", "owner", "severity"], observed=False)
    .agg({
        "harvest_area": "sum",
        "analysis_area": "first",
        "year": "first",
        "ecoregion": "first",
    })
    .reset_index()
)

### Annual Trends

Calculate annual trends by owner and severity class from the raw data.

In [4]:
# Annual harvest trends by individual owner (e.g. USFS) and severity class
owner_trends = (
    df_all_timings.drop(columns=["event_id", "ecoregion"])
    .groupby(["year", "owner", "severity"], observed=False)
    .agg("sum")
    .reset_index()
)

# Annual harvest trends by owner group (e.g. federal) and severity class
owner_group_trends = (
    owner_trends.assign(owner=lambda x: x["owner"].map(OWNER_GROUPS))
    .groupby(["year", "owner", "severity"], observed=False)
    .agg("sum")
    .reset_index()
)

# Calculate trends for all owners
all_owner_trends = (
    owner_trends.groupby(["year", "severity"], observed=False)
    .agg("sum")
    .reset_index()
    .assign(owner="Total")
)

# Append the "All" owner group to the owner group trends
owner_group_trends = pd.concat([owner_group_trends, all_owner_trends])
owner_group_trends["harvest_rate"] = (
    owner_group_trends["harvest_area"] / owner_group_trends["analysis_area"]
).fillna(0)

Export annual trends by owner and severity class for time series analysis in R.

In [42]:
owner_trends.to_csv("../data/results/owner_trends.csv", index=False)
owner_group_trends.to_csv("../data/results/owner_group_trends.csv", index=False)

## Results

### Harvest Timing

Summarize timing of harvests overall and by ownerships.

In [7]:
timing_df = (
    df.drop(columns=["ecoregion", "year"])
    .groupby(["timing", "owner_group", "severity"], observed=False)
    .agg("sum")
    .reset_index()
)

owner_timing_summary = (
    timing_df.groupby(["timing", "owner_group"])
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
)
total_salvage = (
    owner_timing_summary.groupby(["timing"])
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
    .assign(owner_group="Total")
)
owner_timing_summary = pd.concat(
    [owner_timing_summary, total_salvage], axis=0, ignore_index=True
).sort_values(["owner_group", "timing"])

owner_timing_summary["percent_of_harvest"] = (
    owner_timing_summary.groupby("owner_group")["harvest_area"]
    .apply(lambda x: x / x.sum())
    .values
)

Print summary stats by owner.

In [8]:
for owner in ["Total", "Federal", "Private"]:
    owner_timing = owner_timing_summary[owner_timing_summary.owner_group.eq(owner)]
    pct_in_y1 = owner_timing[owner_timing.timing.eq(1)].percent_of_harvest.values[0]
    pct_after_y3 = 1 - owner_timing[owner_timing.timing.lt(4)].percent_of_harvest.sum()

    print(f"{owner}: {pct_in_y1:.0%} in year 1, {pct_after_y3:.0%} after year 3")

Total: 66% in year 1, 9% after year 3
Federal: 54% in year 1, 11% after year 3
Private: 74% in year 1, 8% after year 3

### Total Area

How much total harvest area was predicted?

In [9]:
harvest_ha = owner_trends.harvest_area.sum()
analysis_ha = owner_trends.analysis_area.sum()
overal_harvest_rate = harvest_ha / analysis_ha

print(
    f"We mapped {harvest_ha / 1e3:.0f}k hectares of post-fire harvest across "
    f"{analysis_ha / 1e6:.1f}M hectares of burned forest ({overal_harvest_rate:.1%})."
)

We mapped 178k hectares of post-fire harvest across 2.2M hectares of burned forest (8.0%).

### Area Summary by Owner

Summarize total area analyzed and harvests by owner and owner groups.

In [10]:
owner_summary = (
    owner_trends.groupby(["owner"])
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
    .assign(pct_of_total=lambda x: x["analysis_area"] / x["analysis_area"].sum())
)

owner_group_summary = (
    owner_group_trends[owner_group_trends.owner.ne("Total")]
    .copy()
    .groupby(["owner"])
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
    .assign(pct_of_total=lambda x: x["analysis_area"] / x["analysis_area"].sum())
)

In [11]:
owner_summary

           owner  harvest_area  analysis_area  pct_of_total
0            blm   8096.833787   1.744313e+05      0.078202
1  nonfed_public   3882.519422   5.672858e+04      0.025433
2      other_fed     27.975139   1.193834e+03      0.000535
3        private  88535.606585   4.751147e+05      0.213005
4         tribal   5455.407125   6.590325e+04      0.029546
5           usfs  71689.891180   1.457159e+06      0.653279

In [12]:
owner_group_summary

     owner  harvest_area  analysis_area  pct_of_total
0  Federal  79814.700107   1.632784e+06      0.732016
1    Other   9337.926547   1.226318e+05      0.054979
2  Private  88535.606585   4.751147e+05      0.213005

### Area Trends by Ecoregion

Calculate annual trends by ecoregion.

In [24]:
ecoregion_trends = (
    df_all_timings.assign(owner_group=df_all_timings.owner.map(OWNER_GROUPS))
    .groupby(["ecoregion", "owner_group", "year"])
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
)

ecoregion_trends.to_csv("../data/results/ecoregion_owner_trends.csv", index=False)

Summarize trends by ecoregion.

In [25]:
ecoregion_summary = (
    ecoregion_trends.groupby("ecoregion")
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
    .assign(harvest_rate=lambda x: x["harvest_area"] / x["analysis_area"])
    .assign(pct_of_analysis=lambda x: x["analysis_area"] / x["analysis_area"].sum())
)

ecoregion_summary

,ecoregion,harvest_area,analysis_area,harvest_rate,pct_of_analysis
0,Blue Mountains,17569.001406,339787.912762,0.051706,0.152335
1,Eastern Cascades,56766.549350,524345.247791,0.108262,0.235076
2,Klamath Mountains,39419.619678,568543.932529,0.069334,0.254892
3,Sierra Nevada,55430.579866,627339.399469,0.088358,0.281251
4,Western Cascades,8502.482937,170514.286652,0.049864,0.076446

## Trends by Harvest Year

Rather than looking at harvest trends by *fire year*, we may want to look by *harvest year*, since that should be driven more closely by policy.

Calculating the area harvested in each year is simple, but calculating the area available for harvest in order to get harvest rates is trickier. Currently, the code below uses the total area burned in the five preceding years, minus the area already harvested in those years. For example, the analysis area for 2016 is calculated as follows:

Analysis area in 2016:
- Analysis area in 2011 - area harvested in 2011-2016
- Analysis area in 2012 - area harvested in 2012-2016
- Analysis area in 2013 - area harvested in 2013-2016
- Analysis area in 2014 - area harvested in 2014-2016
- Analysis area in 2015 - area harvested in 2015-2016


This inherently includes more analysis area and produces lower harvest rates than the fire year analysis because each harvest year has access to five years of burned area.

In [4]:
df = pd.read_csv("../data/results/stratified_results.csv").drop(
    columns=["system:index", ".geo"]
)

# Remove unmanaged lands from analysis
df = df[~df["owner"].isin(["wilderness", "nps"])]

# Assign owner groups
df["owner_group"] = df["owner"].map(OWNER_GROUPS)

# Assign severity categories
df["severity"] = pd.Categorical(
    df["severity"], categories=["Very low", "Low", "Moderate", "High"], ordered=True
)
# Check for incorrect severity category names which will produce NAs
assert not df.isna().any().any(), "Check severity category names!"

df["harvest_year"] = df["year"] + df["timing"]

# # Collapse all timings to simplify future processing where having multiple timings
# # could lead to multi-counting areas.
# df_all_timings = (
#     df.groupby(["event_id", "owner", "severity"], observed=False)
#     .agg({
#         "harvest_area": "sum",
#         "analysis_area": "first",
#         "year": "first",
#         "ecoregion": "first",
#     })
#     .reset_index()
# )

# df_all_events = (
#     df.groupby(["owner", "severity", "timing"], observed=False)
#     .agg({
#         "harvest_area": "sum",
#         "analysis_area": "first",
#         "year": "first",
#         "ecoregion": "first",
#     })
#     .reset_index()
# )

The analysis area in each strata for each harvest year should be the total analysis area (excluding recounted areas) for that strata in the past 5 years, minus the area already harvested in that strata in the past 5 years.

In [5]:
annual_timing_summary = (
    df.groupby(
        ["year", "timing", "owner_group", "severity", "ecoregion"], observed=False
    )
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
)
annual_timing_summary["harvest_year"] = (
    annual_timing_summary["year"] + annual_timing_summary["timing"]
)
annual_timing_summary

,year,timing,owner_group,severity,ecoregion,harvest_area,analysis_area,harvest_year
0,1986,1,Federal,Very low,Blue Mountains,22.487401,2358.978418,1987
1,1986,1,Federal,Very low,Eastern Cascades,0.000000,0.000000,1987
2,1986,1,Federal,Very low,Klamath Mountains,0.000000,0.000000,1987
3,1986,1,Federal,Very low,Sierra Nevada,0.000000,55.758253,1987
4,1986,1,Federal,Very low,Western Cascades,0.000000,0.000000,1987
...,...,...,...,...,...,...,...,...
9595,2017,5,Private,High,Blue Mountains,0.000000,0.000000,2022
9596,2017,5,Private,High,Eastern Cascades,0.000000,359.802314,2022
9597,2017,5,Private,High,Klamath Mountains,15.915253,3879.391792,2022
9598,2017,5,Private,High,Sierra Nevada,20.532327,6321.481770,2022
9599,2017,5,Private,High,Western Cascades,0.122092,845.370133,2022

In [6]:
# Sort the dataframe by event_id, owner_group, severity, and harvest_year
annual_timing_summary = annual_timing_summary.sort_values(
    by=["harvest_year", "owner_group", "severity"]
)


# Count the cumulative harvest in each fire year
annual_timing_summary["cumulative_harvest"] = annual_harvest_area = (
    annual_timing_summary.groupby(
        ["year", "owner_group", "severity", "ecoregion"], observed=True
    )["harvest_area"].transform("cumsum")
)


# Shift the cumulative_harvest column by 1 to get the previous year's cumulative harvest
annual_timing_summary["prev_cumulative_harvest"] = (
    annual_timing_summary.groupby(
        ["year", "owner_group", "severity", "ecoregion"], observed=True
    )["cumulative_harvest"]
    .shift(1)
    .fillna(0)
)

# Calculate the adjusted analysis area
annual_timing_summary["adjusted_analysis_area"] = (
    annual_timing_summary["analysis_area"]
    - annual_timing_summary["prev_cumulative_harvest"]
)

# How many years of fire data were available for each harvest year?
annual_timing_summary["analysis_years"] = annual_timing_summary.groupby(
    ["harvest_year", "owner_group", "severity", "ecoregion"], observed=True
)["year"].transform("count")

In [94]:
harvest_year_summary = (
    annual_timing_summary.groupby(
        ["harvest_year", "owner_group", "severity", "ecoregion"], observed=True
    )
    .agg({
        "harvest_area": "sum",
        "adjusted_analysis_area": "sum",
        "analysis_years": "first",
    })
    .reset_index()
)
harvest_year_trends = (
    annual_timing_summary.groupby(["harvest_year", "owner_group"])
    .agg({
        "harvest_area": "sum",
        "adjusted_analysis_area": "sum",
        "analysis_years": "first",
    })
    .reset_index()
)
harvest_year_trends["harvest_rate"] = (
    harvest_year_trends["harvest_area"] / harvest_year_trends["adjusted_analysis_area"]
).fillna(0)
harvest_year_trends = harvest_year_trends.rename(
    columns={
        "harvest_year": "year",
        "owner_group": "owner",
        "adjusted_analysis_area": "analysis_area",
    }
)

# Harvest years at the beginning and end of the dataset don't have 5 years of data, so
# their analysis area isn't comparable to the other years
harvest_year_trends = harvest_year_trends[
    harvest_year_trends.analysis_years.eq(5)
].drop(columns=["analysis_years"])

fire_year_trends = (
    owner_group_trends[~owner_group_trends.owner.isin(["Other", "Total"])]
    .groupby(["year", "owner"])
    .agg({"harvest_area": "sum", "analysis_area": "sum"})
    .reset_index()
    .assign(harvest_rate=lambda x: x["harvest_area"] / x["analysis_area"])
)

year_trend_comparison = pd.concat([
    harvest_year_trends.assign(timing="harvest_year"),
    fire_year_trends.assign(timing="fire_year"),
])

In [95]:
year_trend_comparison

    year    owner  harvest_area  analysis_area  harvest_rate        timing
12  1991  Federal   3904.650339  199655.728327      0.019557  harvest_year
13  1991    Other      9.916955    3631.212197      0.002731  harvest_year
14  1991  Private   1548.960277   56106.631238      0.027607  harvest_year
15  1992  Federal   3042.136276  186522.380557      0.016310  harvest_year
16  1992    Other     13.334856    3533.456306      0.003774  harvest_year
..   ...      ...           ...            ...           ...           ...
59  2015  Private   5781.131215   54284.777794      0.106496     fire_year
60  2016  Federal   1308.920271   37704.695933      0.034715     fire_year
61  2016  Private   1544.273271    8137.365034      0.189776     fire_year
62  2017  Federal   4378.136939  159250.138150      0.027492     fire_year
63  2017  Private   5348.761839   27265.304173      0.196175     fire_year

[148 rows x 6 columns]

In [101]:
fig = px.line(
    year_trend_comparison[year_trend_comparison.owner.ne("Other")],
    x="year",
    y="harvest_rate",
    color="owner",
    facet_row="timing",
    width=800,
)

fig.update_yaxes(matches=None)

In [102]:
fig = px.line(
    year_trend_comparison[year_trend_comparison.owner.ne("Other")],
    x="year",
    y="harvest_area",
    color="owner",
    facet_row="timing",
    width=800,
)

fig.update_yaxes(matches=None)